# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /data/home/zkofira/temp-0618/truescan

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /data/home/zkofira/temp-0618/truescan

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /data/home/zkofira/temp-0618/truescan/CMakeFiles /data/home/zkofira/temp-0618/truescan//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /data/home/zkofira/temp-0618/truescan/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Distance_SCAN_SIGMOD

# Build rule for target.
Distance_SCAN_SIGMOD: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Distance_SCAN_SIGMOD
.PHONY : Distance_SCAN_SIGMOD

# fast build rule for target.
Distance_SCAN_SIGMOD/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Distance_SCAN_SIGMOD.dir/build.make CMakeFiles/Distance_SCAN_SIGMOD.dir/build
.PHONY : Distance_SCAN_SIGMOD/fast

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Distance_SCAN_SIGMOD.dir/build.make CMakeFiles/Distance_SCAN_SIGMOD.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Distance_SCAN_SIGMOD.dir/build.make CMakeFiles/Distance_SCAN_SIGMOD.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Distance_SCAN_SIGMOD.dir/build.make CMakeFiles/Distance_SCAN_SIGMOD.dir/main.cpp.s
.PHONY : main.cpp.s

src/binary_tree.o: src/binary_tree.cpp.o
.PHONY : src/binary_tree.o

# target to build an object file
src/binary_tree.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Distance_SCAN_SIGMOD.dir/build.make CMakeFiles/Distance_SCAN_SIGMOD.dir/src/binary_tree.cpp.o
.PHONY : src/binary_tree.cpp.o

src/binary_tree.i: src/binary_tree.cpp.i
.PHONY : src/binary_tree.i

# target to preprocess a source file
src/binary_tree.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Distance_SCAN_SIGMOD.dir/build.make CMakeFiles/Distance_SCAN_SIGMOD.dir/src/binary_tree.cpp.i
.PHONY : src/binary_tree.cpp.i

src/binary_tree.s: src/binary_tree.cpp.s
.PHONY : src/binary_tree.s

# target to generate assembly for a file
src/binary_tree.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Distance_SCAN_SIGMOD.dir/build.make CMakeFiles/Distance_SCAN_SIGMOD.dir/src/binary_tree.cpp.s
.PHONY : src/binary_tree.cpp.s

src/clusteralgo.o: src/clusteralgo.cpp.o
.PHONY : src/clusteralgo.o

# target to build an object file
src/clusteralgo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Distance_SCAN_SIGMOD.dir/build.make CMakeFiles/Distance_SCAN_SIGMOD.dir/src/clusteralgo.cpp.o
.PHONY : src/clusteralgo.cpp.o

src/clusteralgo.i: src/clusteralgo.cpp.i
.PHONY : src/clusteralgo.i

# target to preprocess a source file
src/clusteralgo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Distance_SCAN_SIGMOD.dir/build.make CMakeFiles/Distance_SCAN_SIGMOD.dir/src/clusteralgo.cpp.i
.PHONY : src/clusteralgo.cpp.i

src/clusteralgo.s: src/clusteralgo.cpp.s
.PHONY : src/clusteralgo.s

# target to generate assembly for a file
src/clusteralgo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Distance_SCAN_SIGMOD.dir/build.make CMakeFiles/Distance_SCAN_SIGMOD.dir/src/clusteralgo.cpp.s
.PHONY : src/clusteralgo.cpp.s

src/config.o: src/config.cpp.o
.PHONY : src/config.o

# target to build an object file
src/config.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Distance_SCAN_SIGMOD.dir/build.make CMakeFiles/Distance_SCAN_SIGMOD.dir/src/config.cpp.o
.PHONY : src/config.cpp.o

src/config.i: src/config.cpp.i
.PHONY : src/config.i

# target to preprocess a source file
src/config.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Distance_SCAN_SIGMOD.dir/build.make CMakeFiles/Distance_SCAN_SIGMOD.dir/src/config.cpp.i
.PHONY : src/config.cpp.i

src/config.s: src/config.cpp.s
.PHONY : src/config.s

# target to generate assembly for a file
src/config.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Distance_SCAN_SIGMOD.dir/build.make CMakeFiles/Distance_SCAN_SIGMOD.dir/src/config.cpp.s
.PHONY : src/config.cpp.s

src/fhq_treap.o: src/fhq_treap.cpp.o
.PHONY : src/fhq_treap.o

# target to build an object file
src/fhq_treap.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Distance_SCAN_SIGMOD.dir/build.make CMakeFiles/Distance_SCAN_SIGMOD.dir/src/fhq_treap.cpp.o
.PHONY : src/fhq_treap.cpp.o

src/fhq_treap.i: src/fhq_treap.cpp.i
.PHONY : src/fhq_treap.i

# target to preprocess a source file
src/fhq_treap.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Distance_SCAN_SIGMOD.dir/build.make CMakeFiles/Distance_SCAN_SIGMOD.dir/src/fhq_treap.cpp.i
.PHONY : src/fhq_treap.cpp.i

src/fhq_treap.s: src/fhq_treap.cpp.s
.PHONY : src/fhq_treap.s

# target to generate assembly for a file
src/fhq_treap.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Distance_SCAN_SIGMOD.dir/build.make CMakeFiles/Distance_SCAN_SIGMOD.dir/src/fhq_treap.cpp.s
.PHONY : src/fhq_treap.cpp.s

src/graph.o: src/graph.cpp.o
.PHONY : src/graph.o

# target to build an object file
src/graph.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Distance_SCAN_SIGMOD.dir/build.make CMakeFiles/Distance_SCAN_SIGMOD.dir/src/graph.cpp.o
.PHONY : src/graph.cpp.o

src/graph.i: src/graph.cpp.i
.PHONY : src/graph.i

# target to preprocess a source file
src/graph.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Distance_SCAN_SIGMOD.dir/build.make CMakeFiles/Distance_SCAN_SIGMOD.dir/src/graph.cpp.i
.PHONY : src/graph.cpp.i

src/graph.s: src/graph.cpp.s
.PHONY : src/graph.s

# target to generate assembly for a file
src/graph.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Distance_SCAN_SIGMOD.dir/build.make CMakeFiles/Distance_SCAN_SIGMOD.dir/src/graph.cpp.s
.PHONY : src/graph.cpp.s

src/mylib.o: src/mylib.cpp.o
.PHONY : src/mylib.o

# target to build an object file
src/mylib.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Distance_SCAN_SIGMOD.dir/build.make CMakeFiles/Distance_SCAN_SIGMOD.dir/src/mylib.cpp.o
.PHONY : src/mylib.cpp.o

src/mylib.i: src/mylib.cpp.i
.PHONY : src/mylib.i

# target to preprocess a source file
src/mylib.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Distance_SCAN_SIGMOD.dir/build.make CMakeFiles/Distance_SCAN_SIGMOD.dir/src/mylib.cpp.i
.PHONY : src/mylib.cpp.i

src/mylib.s: src/mylib.cpp.s
.PHONY : src/mylib.s

# target to generate assembly for a file
src/mylib.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Distance_SCAN_SIGMOD.dir/build.make CMakeFiles/Distance_SCAN_SIGMOD.dir/src/mylib.cpp.s
.PHONY : src/mylib.cpp.s

src/sketches.o: src/sketches.cpp.o
.PHONY : src/sketches.o

# target to build an object file
src/sketches.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Distance_SCAN_SIGMOD.dir/build.make CMakeFiles/Distance_SCAN_SIGMOD.dir/src/sketches.cpp.o
.PHONY : src/sketches.cpp.o

src/sketches.i: src/sketches.cpp.i
.PHONY : src/sketches.i

# target to preprocess a source file
src/sketches.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Distance_SCAN_SIGMOD.dir/build.make CMakeFiles/Distance_SCAN_SIGMOD.dir/src/sketches.cpp.i
.PHONY : src/sketches.cpp.i

src/sketches.s: src/sketches.cpp.s
.PHONY : src/sketches.s

# target to generate assembly for a file
src/sketches.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Distance_SCAN_SIGMOD.dir/build.make CMakeFiles/Distance_SCAN_SIGMOD.dir/src/sketches.cpp.s
.PHONY : src/sketches.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Distance_SCAN_SIGMOD"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/binary_tree.o"
	@echo "... src/binary_tree.i"
	@echo "... src/binary_tree.s"
	@echo "... src/clusteralgo.o"
	@echo "... src/clusteralgo.i"
	@echo "... src/clusteralgo.s"
	@echo "... src/config.o"
	@echo "... src/config.i"
	@echo "... src/config.s"
	@echo "... src/fhq_treap.o"
	@echo "... src/fhq_treap.i"
	@echo "... src/fhq_treap.s"
	@echo "... src/graph.o"
	@echo "... src/graph.i"
	@echo "... src/graph.s"
	@echo "... src/mylib.o"
	@echo "... src/mylib.i"
	@echo "... src/mylib.s"
	@echo "... src/sketches.o"
	@echo "... src/sketches.i"
	@echo "... src/sketches.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

